name: flutter_game
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  flame: ^1.8.2
  flame_bloc: ^1.10.3
  flame_audio: ^2.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flame_tiled: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/audio/tetris/
    - assets/audio/mario/
    - assets/images/
    - assets/images/tetris/
    - assets/images/mario/
    - assets/tiles/